/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 public/models/cargo.gltf -o src/components/Ships.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Cargo({ active, onSelect, name, ...props }) {
  const { nodes, materials } = useGLTF("/models/cargo.gltf");
  return (
    <group {...props} dispose={null} onClick={onSelect}>
      <mesh
        geometry={nodes.Spaceship_FinnTheFrog.geometry}
        material={materials.Atlas}
      />
    </group>
  );
}

useGLTF.preload("/models/cargo.gltf");
