/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 public/models/rogue.gltf -o src/components/Ships/Rogue.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Rogue({ active, onSelect, name, ...props }) {
  const { nodes, materials } = useGLTF("/models/rogue.gltf");
  return (
    <group {...props} dispose={null} onClick={onSelect}>
      <mesh
        geometry={nodes.Spaceship_RaeTheRedPanda.geometry}
        material={materials.Atlas}
      />
    </group>
  );
}

useGLTF.preload("/models/rogue.gltf");
