/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 public/models/pink.gltf -o src/components/Ships/Pink.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Scout(props) {
  const { nodes, materials } = useGLTF("/models/pink.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Spaceship_FernandoTheFlamingo.geometry}
        material={materials.Atlas}
      />
    </group>
  );
}

useGLTF.preload("/models/pink.gltf");
