/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.9 public/models/time.gltf -o src/components/Ships/Time.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Time = React.forwardRef(({ active, onSelect, name, ...props }, ref) => {
  const { nodes, materials } = useGLTF("/models/time.gltf");
  return (
    <group {...props} dispose={null} onClick={onSelect} ref={ref}>
      <mesh
        geometry={nodes.Spaceship_BarbaraTheBee.geometry}
        material={materials.Atlas}
      />
    </group>
  );
});

useGLTF.preload("/models/time.gltf");

export default Time;
